# Конфигурация Graph Viewer для fedoc
# Документация: docs/graph-viewer-setup.md
version: "2.0"

# Удаленный сервер (общий для всех машин)
remote_server:
  host: "176.108.244.252"
  user: "user1"
  ssh_alias: "fedoc-server"
  description: "Production сервер с PostgreSQL + Apache AGE"

# Порты (общие для всех, можно переопределить в профиле машины)
ports:
  # SSH туннели
  postgres_tunnel: 15432    # Локальный порт для PostgreSQL туннеля
  arango_tunnel: 8529       # Локальный порт для ArangoDB туннеля (legacy)
  
  # Сервисы
  api_server: 15000         # REST API для графов (исправлено с 8899)
  vite_server: 5173         # Vue.js dev сервер

# PostgreSQL настройки (основная БД)
postgres:
  enabled: true
  port: 5432                # Порт на удаленном сервере
  host: "localhost"         # Через SSH туннель
  database: "fedoc"
  user: "postgres"
  password_env: "POSTGRES_PASSWORD"  # Переменная окружения
  default_password: "fedoc_test_2025"  # Пароль по умолчанию

# ArangoDB настройки (legacy, только для миграции)
arango:
  enabled: false            # Отключено после миграции на PostgreSQL
  port: 8529
  host: "http://localhost:8529"  # Через SSH туннель
  database: "fedoc"
  user: "root"
  password_env: "ARANGO_PASSWORD"  # Имя переменной окружения с паролем

# Пути относительно корня проекта (могут быть переопределены в профиле)
paths:
  frontend: "src/lib/graph_viewer/frontend"
  backend: "src/lib/graph_viewer/backend"
  venv_python: "venv/bin/python"  # Относительный путь от project_root

# Логи
logs:
  api_server: "/tmp/graph_viewer_api.log"
  vite_server: "/tmp/graph_viewer_vite.log"
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR

# Опции по умолчанию
options:
  auto_install_npm: false         # Спрашивать у пользователя
  auto_create_ssh_config: true    # Автоматически создавать SSH config
  auto_create_ssh_key: false      # Спрашивать у пользователя
  check_dependencies: true        # Проверять зависимости перед запуском
  timeout_seconds: 30             # Таймаут запуска компонентов
  auto_open_browser: true         # Открывать браузер после запуска

# Профили машин
machines:
  enabled: true
  auto_detect: true               # Автоопределение по {user}-{hostname}
  ask_if_unknown: true            # Спрашивать параметры для новой машины
  directory: "config/machines"    # Где искать профили
  save_new_profiles: true         # Сохранять новые профили автоматически



