# Профиль машины: alex-User-PC (Windows WSL2)
# Рабочая машина с WSL2
machine:
  hostname: "User-PC"
  username: "alex"
  os: "WSL2"
  distribution: "Ubuntu 24.04"
  description: "Windows с WSL2 Ubuntu"
  added: "2025-10-20"

# SSH настройки
ssh:
  key_path: "~/.ssh/id_ed25519"
  config_path: "~/.ssh/config"

# Пути к инструментам
tools:
  python: "/usr/bin/python3"
  node: "/usr/bin/node"
  npm: "/usr/bin/npm"

# Пути проекта (абсолютные)
project:
  root: "/home/alex/fedoc"
  venv: "/home/alex/fedoc/venv"

# Особенности окружения
environment:
  shell: "/bin/bash"
  # В WSL нужно открывать браузер через cmd.exe
  browser_command: "cd /mnt/c && cmd.exe /c start"
  
# Опции для этой машины
options:
  auto_open_browser: true
  verbose_logging: false

# Примечания
# - Браузер открывается через cmd.exe из Windows
# - SSH туннели работают нормально
# - npm зависимости установлены
# - PostgreSQL доступен через SSH туннель на порту 15432
